version: '3'

services:
  xfreerdp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: tail -f /dev/null
    network_mode: host
    privileged: true
